### ISSUE TITLE
Unrecognized command line option '-m64' for ARM64 build

### ISSUE THREAD

**Issue by peter197321** [KhronosGroup/OpenVX-sample-impl#13]
Is it possible to build this sample implementation of OpenVX for arm64/Linux?

Unfortunately, during compilation I got error

> gcc: error: unrecognized command line option '-m64'

**Comment by kiritigowda** [comment]
@peter197321 now the OpenVX 1.3 sample builds and runs on raspberry pi

**Comment by kiritigowda** [comment]
@peter197321 can you let me know if OpenVX 1.3 worked for you on ARM?

Instructions to build on ARM - https://github.com/KhronosGroup/OpenVX-sample-impl#sample-2---build-openvx-13-on-raspberry-pi

**Comment by kiritigowda** [comment]
@peter197321 please reopen if you still have issues building on ARM.
