### ISSUE TITLE
fatal error: VX/vx.h: No such file or directory

### ISSUE THREAD

**Issue by peter197321** [KhronosGroup/OpenVX-sample-impl#14]
By 

> :~/tmp/OpenVX-sample-impl$ python Build.py --os=Linux --arch=64

getting 

```
OpenVX-sample-impl/kernels/debug/debug_k.h:21:10: fatal error: VX/vx.h: No such file or directory
 #include <VX/vx.h>
          ^~~~~~~~~
compilation terminated.
```
can u help?

**Comment by bhargavthriler** [comment]
> By
> 
> > :~/tmp/OpenVX-sample-impl$ python Build.py --os=Linux --arch=64
> 
> getting
> 
> ```
> OpenVX-sample-impl/kernels/debug/debug_k.h:21:10: fatal error: VX/vx.h: No such file or directory
>  #include <VX/vx.h>
>           ^~~~~~~~~
> compilation terminated.
> ```
> 
> can u help?

Take the header files from this repo: https://github.com/KhronosGroup/OpenVX-api-docs.git

**Comment by kiritigowda** [comment]
@peter197321 Please follow the build procedures followed on our Travis CI to build and run conformance - https://travis-ci.com/KhronosGroup/OpenVX-sample-impl

The commands below to run conformance for Vision
```
git clone https://github.com/KhronosGroup/OpenVX-sample-impl.git
cd OpenVX-sample-impl
git submodule sync --recursive
git submodule update --init --recursive --remote
mkdir build-cts-mode-1
python Build.py --os=Linux --arch=64 --conf=Debug --conf_vision
cd build-cts-mode-1
cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include -DOPENVX_LIBRARIES=$OPENVX_DIR/bin/libopenvx.so\;$OPENVX_DIR/bin/libvxu.so\;pthread\;dl\;m\;rt -DOPENVX_CONFORMANCE_VISION=ON ../cts/
cmake --build .
LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance
```

**Comment by arjunskumar** [comment]
@kiritigowda I followed your steps but getting the same eror fatal error: VX/vx.h: No such file or directory
 #include <VX/vx.h>

**Comment by arjunskumar** [comment]
I was able to build Openvx 1.3 on Ubuntu 18.0

```
git clone --recursive https://github.com/KhronosGroup/OpenVX-sample-impl.git
cd OpenVX-sample-impl/
python Build.py --os=Linux --arch=64 --conf=Debug --conf_vision --enh_vision --conf_nn

export OPENVX_DIR=$(pwd)/install/Linux/x64/Debug
export VX_TEST_DATA_PATH=$(pwd)/cts/test_data/
mkdir build-cts
cd build-cts
cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include -DOPENVX_LIBRARIES=$OPENVX_DIR/bin/libopenvx.so\;$OPENVX_DIR/bin/libvxu.so\;pthread\;dl\;m\;rt -DOPENVX_CONFORMANCE_VISION=ON -DOPENVX_USE_ENHANCED_VISION=ON -DOPENVX_CONFORMANCE_NEURAL_NETWORKS=ON ../cts/
cmake --build .
LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance
```

**Comment by SijinJohn** [comment]
I am getting this error on raspberry pi 3.

**Comment by SijinJohn** [comment]
/home/pi/OpenVX/OpenVX-sample-impl/cts/test_engine/test_utils.h:21:10: fatal error: VX/vx.h: No such file or directory
#include <VX/vx.h>
^~~~~~~~~
compilation terminated.

**Comment by SijinJohn** [comment]
i followed this 

Use the Build.py script to build and install OpenVX 1.3
cd OpenVX-sample-impl/
python Build.py --os=Linux --venum --conf=Debug --conf_vision --enh_vision --conf_nn

Build and run the conformance:

export OPENVX_DIR=$(pwd)/install/Linux/x32/Debug
export VX_TEST_DATA_PATH=$(pwd)/cts/test_data/
mkdir build-cts
cd build-cts
cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include -DOPENVX_LIBRARIES=$OPENVX_DIR/bin/libopenvx.so\;$OPENVX_DIR/bin/libvxu.so\;pthread\;dl\;m\;rt -DOPENVX_CONFORMANCE_VISION=ON -DOPENVX_USE_ENHANCED_VISION=ON -DOPENVX_CONFORMANCE_NEURAL_NETWORKS=ON ../cts/
cmake --build .

**Comment by arjunskumar** [comment]
cd openvx_ws

git clone --recursive https://github.com/KhronosGroup/OpenVX-sample-impl.git

cd OpenVX-sample-impl/

python Build.py --os=Linux --arch=32 --conf=Debug --conf_vision --enh_vision --conf_nn

export OPENVX_DIR=$(pwd)/install/Linux/x32/Debug

export VX_TEST_DATA_PATH=$(pwd)/cts/test_data/

mkdir build-cts

cd build-cts

cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include -DOPENVX_LIBRARIES=$OPENVX_DIR/bin/libopenvx.so\;$OPENVX_DIR/bin/libvxu.so\;pthread\;dl\;m\;rt -DOPENVX_CONFORMANCE_VISION=ON -DOPENVX_USE_ENHANCED_VISION=ON -DOPENVX_CONFORMANCE_NEURAL_NETWORKS=ON ../cts/

cmake --build .

LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance


@SijinJohn Please try this;

**Comment by SijinJohn** [comment]
@arjunskumar
python Build.py --os=Linux --arch=32 --conf=Debug --conf_vision --enh_vision --conf_nn
this line didn't work so i added --venum
python Build.py --os=Linux --venum --arch=32 --conf=Debug --conf_vision --enh_vision --conf_nn
After this step.


This step->
cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include -DOPENVX_LIBRARIES=$OPENVX_DIR/bin/libopenvx.so;$OPENVX_DIR/bin/libvxu.so;pthread;dl;m;rt -DOPENVX_CONFORMANCE_VISION=ON -DOPENVX_USE_ENHANCED_VISION=ON -DOPENVX_CONFORMANCE_NEURAL_NETWORKS=ON ../cts/ 
gives error 
CMake Error: The source directory "/home/pi/OpenVX/OpenVX-sample-impl/build-cts" does not appear to contain CMakeLists.txt.

CmakeLists.txt is in OpenVX-sample-impl  not inside build-cts
I am not getting this error.

**Comment by arjunskumar** [comment]
@SijinJohn Can you share the screenshot of error?
