### ISSUE TITLE
Where are the header files?

### ISSUE THREAD

**Issue by stephenramm** [KhronosGroup/OpenVX-sample-impl#7]
Seems there are a few files missing from this repository, has anyone else tried a clean checkout and build?
The path include/VX is a little underpopulated.

**Comment by jessegv** [comment]
They are included in the the api-docs repository, which is a submodule of
this repository.  See:

https://github.com/KhronosGroup/OpenVX-sample-impl/blob/openvx_1.2/.gitmodules

Jesse

**Comment by stephenramm** [comment]
Thanks Jesse!

**Comment by stephenramm** [comment]
Hi Jesse,
I have some examples written in c++ and find they don't compile using the
headers in the submodule, because the #ifdef __cplusplus guards are missing
one of the headers. Doing a diff between what I have and what is in the
submodule there are a lot of differences, and it actually looks like the
submodule stuff is older, which I find surprising. Diff attached FYI.
--

Steve
